### PR TITLE
1_pratham29.cpp

### PR DESCRIPTION
**Pull request by prathamprakash29**
Issue Number #

## Details

 - Language used : c++
 - Link : https://code.hackerearth.com/7729fbm

### CODE REVIEW

**Comment by prathamprakash29** [comment]
done

**Comment by pradeepgangwar** [comment]
I asked to changed file extension not title of the PR.

**Comment by prathamprakash29** [comment]
corrected it

**Comment by pradeepgangwar** [comment]
Learn about squashing commits. This time i am doing for you. Moreover link to hackerearth is wrong. But file looks fine.

**Pull request merged**
