### PR TITLE
C++ solution for issue 1

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Issue Number #1

## Details

 - Language used :C++
 - Link :https://code.hackerearth.com/751f14z

### CODE REVIEW

**Comment by aswinzz** [comment]
your link is empty

**Comment by GOVINDDIXIT** [comment]
Sir,the link is not empty i can visit it

**Comment by GOVINDDIXIT** [comment]
Link is corrected and updated

**Comment by pradeepgangwar** [comment]
Also Write PR title and commit message like. `Add Govind's solution to problem 1`.

**Comment by GOVINDDIXIT** [comment]
Ok Sir,next time i will be more cautious,

**Pull request merged**
