### PR TITLE
solution for day 5

### PR DESCRIPTION
**Pull request by DEVILCODER-SB99**
Issue Number #5

## Details

 - Language used :python 3
 - Link :https://ideone.com/ghyRH7

### CODE REVIEW

**Comment by aswinzz** [comment]
only points for day 5. for other questions time is over

**Comment by aswinzz** [comment]
directory structure is not proper

**Comment by DEVILCODER-SB99** [comment]
sir problem in directory structure is what...please explain...

**Comment by DEVILCODER-SB99** [comment]
@aswinzz

**Pull request closed without merging**
