### PR TITLE
Day-3 And Day-4 Solution Added

### PR DESCRIPTION
**Pull request by abhishhh1**
Issue Number #3

## Details Day-3 and Day-4 Solution

 - Language used : Python 3
 - Link for Day-3 :  https://ideone.com/GiyMBh<li>Link for Day-4 : https://ideone.com/ECC32D

### CODE REVIEW

**Comment by abhishhh1** [comment]
I've changed the directory now

**Comment by pradeepgangwar** [comment]
WA for day 4

**Comment by aswinzz** [comment]
We can't give points for day 3.

**Comment by Anupam-dagar** [comment]
20 points for day 4

**Pull request merged**
