### PR TITLE
#Day 4 solution

### PR DESCRIPTION
**Pull request by nikki1016**
Day 4
Issue Number #75 

## Details

 - Language used : C++ 14 
 - Link : https://ideone.com/zlfMW7

Issue Number #52 
## Details
 - Language used : GO 
 - Link :https://code.hackerearth.com/432cecY

### CODE REVIEW

**Comment by nikki1016** [comment]
Day 5
Issue Number #86 

Details

Language used : C++ 14
Link : https://ideone.com/PMDNQX

**Comment by nikki1016** [comment]
@pradeepgangwar  is solution 4 wrong ?

**Comment by pradeepgangwar** [comment]
@nikki1016 initial check reveals no.

**Comment by aswinzz** [comment]
we cant give points for day 4 since only first 10 PR's will be meged.
for day 5 - 20 points

**Pull request merged**
